services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/n8n-io/n8n
    branch: master
    plan: free
    envVars:
      - key: N8N_HOST
        value: n8n-quantctd.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-quantctd.onrender.com
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: nguyenquan
      - key: N8N_BASIC_AUTH_PASSWORD
        value: @Baolinh2009
